---
# Stackmate project configuration
framework: django
# The repository to deploy from
repository: git@github.com:stackmate-io/sample-app-django3.git
# The cloud provider to use
provider: aws
# The region to deploy to
region: eu-central-1
# The provider credentials to use
providers:
  aws:
    access_key: "{{ lookup('env', 'STACKMATE_ACCESS_KEY') }}"
    secret: "{{ lookup('env', 'STACKMATE_SECRET') }}"
  github:
    access_key: "{{ lookup('env', 'STACKMATE_GITHUB_ID') }}"
    secret: "{{ lookup('env', 'STACKMATE_GITHUB_SECRET') }}"
    token: "{{ lookup('env', 'STACKMATE_GITHUB_TOKEN') }}"
  slack:
    secret: "{{ lookup('env', 'STACKMATE_SLACK_TOKEN') }}"
  email:
    host: smtp.sendgrid.net
    port: 587
    access_key: apikey
    secret: "{{ lookup('env', 'STACKMATE_SENDGRID_TOKEN') }}"

# environments
production:
  # branch to deploy
  branch: master
  # domain to use
  domain: django.ezploy.eu
  # documentroot in the servers
  documentroot: /var/www/django-app

  # deployment pipeline
  pipeline:
    build:
      - pip install -r requirements.txt
      - python manage.py migrate
      - python manage.py collectstatic
    after:
      restart:
        - gunicorn
      reload:
        - nginx
  # services to use
  services:
    - name: django-app-server
      type: application
      size: t2.nano
      dependencies:
        - type: nginx
        - type: gunicorn
        - type: python
      storage: 20

    - name: django-app-mysql-db
      type: mysql
      version: 5.7
      size: db.t3.micro
      storage: 100
      databases:
        - djangoapp
      environment:
        DB_NAME: djangoapp
        DB_USER: "{{username}}"
        DB_HOST: "{{host}}"
        DB_PASS: "{{password}}"

notifications:
  - type: email
    targets:
      - stackmateuser@mailinator.com

  - type: slack
    targets:
      - deployments-channel
