"""Migrations for the incidents"""
# pylint: disaable]
# -*- coding: utf-8 -*-
# Generated by Django 3.0.2 on 2020-04-10 09:23
from datetime import datetime, timedelta
from django.db import migrations, models

INCIDENT_DATA = [{
    'title': 'Elevated error rate for API',
    'is_resolved': True,
    'occurred_at': datetime.now() - timedelta(days=10),
}, {
    'title': 'Web client not responding',
    'is_resolved': True,
    'occurred_at': datetime.now() - timedelta(days=2),
}, {
    'title': 'Elevated error rate for webhook service',
    'is_resolved': False,
    'occurred_at': datetime.now(),
}]

def insert_initial_data(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Incident = apps.get_model('appstatus', 'Incident')

    for entry in INCIDENT_DATA:
        model = Incident(
            title=entry['title'],
            is_resolved=entry['is_resolved'],
            occurred_at=entry['occurred_at'])

        model.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_resolved', models.BooleanField(default=True)),
                ('occurred_at', models.DateField()),
            ],
        ),

        migrations.RunPython(insert_initial_data),
    ]
